import requests
import json
import os
from dotenv import load_dotenv

def build_map():
    load_dotenv()
    api_key = os.getenv("API_BASKETBALL_KEY")

    print("Fetching raw master list from API-Basketball...")
    r = requests.get("https://v1.basketball.api-sports.io/leagues", headers={"x-apisports-key": api_key})
    
    if r.status_code != 200:
        print(f"API Error: {r.text}")
        return
        
    leagues = r.json().get("response", [])
    
    slug_map = {}
    for l in leagues:
        c = l.get("country", {}).get("name", "")
        lname = l.get("name", "")
        lid = l.get("id")
        
        # Omit generic World friendlies as they break physical parsing rules
        if c and lname and c.lower() != "world":
            country_slug = c.lower().strip().replace(" ", "-")
            league_slug = lname.lower().strip().replace(" ", "-")
            
            # Normalize to match the python slug variable format generated by our scraper
            slug = f"{country_slug}_{league_slug}".replace("-", "_").replace(".", "")
            
            # Map the exact Flashscore slug to the required Database API Integer
            slug_map[slug] = lid
            
    os.makedirs("data", exist_ok=True)
    with open("data/league_slug_map.json", "w") as f:
        json.dump(slug_map, f, indent=2)
        
    print(f"Successfully bridged {len(slug_map)} local Flashscore strings to their internal API integers!")

if __name__ == "__main__":
    build_map()
