"""
run_basketball_daily.py
========================
Universal daily basketball prediction runner.
Chains: fixtures -> team stats -> league config -> engine -> predictions output.

Works for ANY league available on api-basketball.com.

Usage:
    python run_basketball_daily.py                         # all leagues today
    python run_basketball_daily.py --league_id 40          # BBL Germany only
    python run_basketball_daily.py --date 2026-03-20       # specific date
    python run_basketball_daily.py --min_games 3           # only leagues with 3+ games
    python run_basketball_daily.py --mode full             # full sharp layer
    python run_basketball_daily.py --refresh               # re-fetch fixtures from API
    python run_basketball_daily.py --trace                 # show engine math trace

Output:
    Console: matchup-by-matchup prediction table
    File:    data/basketball_predictions_YYYY-MM-DD.json
"""

import io
import sys
import os
import json
import argparse
import requests
import math
import glob
from datetime import datetime, timezone, timedelta
from zoneinfo import ZoneInfo
from dotenv import load_dotenv
from scipy.stats import norm

from core.offline_match_center import compile_offline_match_center
from core.confidence_score import compute_confidence
from run_confidence_report import load_leaderboard, get_team_stats

if sys.platform == "win32":
    try:
        sys.stdout.reconfigure(encoding="utf-8")
    except AttributeError:
        pass  # Python < 3.7

# Add project root
sys.path.append(os.path.abspath(os.path.dirname(__file__)))
load_dotenv()

API_KEY = os.getenv("API_BASKETBALL_KEY")
BASE_URL = "https://v1.basketball.api-sports.io"
HEADERS = {"x-apisports-key": API_KEY}
ET_TZ    = timezone.utc


# ------------------------------------------------------------------
# LEAGUES EXCLUDED FROM THIS RUNNER
# ONLY USA Leagues are excluded, as they are covered by dedicated scripts.
# ------------------------------------------------------------------
EXCLUDED_LEAGUE_IDS = set()
EXCLUDED_LEAGUE_NAMES = set()


# ------------------------------------------------------------------
# HELPERS
# ------------------------------------------------------------------

TEAM_NAME_OVERRIDES = {
    "Psychikou": "Psyhiko Athens",
    "Trikala": "Am Ikaroi Trikalon",
    "BK Zaporozhye": "Zaporizhye",
    "Escolar Aleman": "Aleman",
    "Beeliar Boodjar": "Cockburn",
    "Mandurah Magic": "Mandurah",
    "Cockburn Cougars": "Cockburn",
    "Turan Turkistan": "Turan",
    # --- Australia NBL1 (Multiple Regions) ---
    "Penrith P.":                  "Penrith Panthers",
    "Penrith P. W":                "Penrith Panthers",
    "Hornsby S.":                  "Hornsby Ku-Ring-Gai Spiders",
    "Hornsby S. W":                "Hornsby Ku-Ring-Gai Spiders",
    "Manly W.":                    "Manly Warringah Sea Eagles",
    "Manly W. W":                  "Manly Warringah Sea Eagles",
    "Maitland M.":                 "Maitland Mustangs",
    "Albury W":                    "Albury-Wodonga Bandits",
    "Southern District":           "Southern District Spartans",
    "Warwick Senators":            "Warwick Senators",
    "Willetton Tigers":            "Willetton Tigers",
    "Lakeside Lightning":          "Lakeside Lightning",
    "Perry Lakes Hawks":           "Perry Lakes Hawks",
    "Rockingham Flames":           "Rockingham Flames",
    "Joondalup Wolves":            "Joondalup Wolves",
    "Geraldton Buccaneers":        "Geraldton Buccaneers",
    "Goldfields Giants":           "Goldfields Giants",
    "Nunawading Spectres":         "Nunawading Spectres",
    "Frankston Blues":             "Frankston Blues",
    "Geelong United":              "Geelong United",
    "Kilsyth Cobras":              "Kilsyth Cobras",
    "Ballarat Miners":             "Ballarat Miners",
    "Dandenong Rangers":           "Dandenong Rangers",
    "Diamond Valley Eagles":       "Diamond Valley Eagles",
    "Eltham Wildcats":             "Eltham Wildcats",
    "Knox Raiders":                "Knox Raiders",
    "Ringwood Hawks":              "Ringwood Hawks",
    "Waverley Falcons":            "Waverley Falcons",
    "Perth Redbacks":              "Perth Redbacks",
    "East Perth Eagles":           "East Perth Eagles",

    # --- Australia NBL1 North Men (207) ---
    # Maps API prediction names → stats file canonical names (generated by generate_advanced_metrics.py)
    "Gold Coast Rollers":          "Gold Coast Rollers",   # Fixed: no longer merges into North Gold Coast
    "Cairns Marlins":              "Cairns",
    "Ipswich Force":               "Ipswich",
    "Logan Thunder":               "Logan",
    "Mackay Meteors":              "Mackay",
    "Northside Wizards":           "Northside",
    "Rockhampton Rockets":         "Rockhampton",
    "Townsville Heat":             "Townsville",
    "SW Metro Pirates":            "South West Metro Pirates",
    # Brisbane Capitals, Sunshine Coast Phoenix, North Gold Coast Seahawks, Southern District Spartans
    # all match the stats file exactly — no override needed. Southern District → line 86 above.

    # --- Australia NBL1 North Women (208) ---
    "Gold Coast Rollers W":        "Gold Coast Rollers W",
    "Cairns W":                    "Cairns",
    "Ipswich Force W":             "Ipswich",
    "Logan Thunder W":             "Logan",
    "Mackay Meteorettes W":        "Mackay",
    "Northside Wizards W":         "Northside",
    "Rockhampton Cyclones W":      "Rockhampton W",
    "Townsville Flames W":         "Townsville",
    "SW Metro Pirates W":          "South West Metro Pirates W",
    "Brisbane Capitals W":         "Brisbane Capitals",
    "Sunshine Coast Phoenix W":    "Sunshine Coast Phoenix",
    "Southern District Spartans W": "Southern District Spartans",
    "North Gold Coast Seahawks W": "North Gold Coast Seahawks",

    # --- Austria Superliga (217) ---
    "Graz UBSC": "UBSC Raiffeisen Graz",
    "BBC Nord": "Eisenstadt Dragonz",
    "Furstenfeld": "Panthers Fürstenfeld",
    "Vienna Basket": "BC Vienna",
    "Klosterneuburg Dukes": "BK Dukes",
    "Wels": "Raiffeisen Flyers Wels",
    "Oberwart Gunners": "Unger Steel Gunners Oberwart",
    # --- Iceland Premier League (48) ---
    "KR Basket": "KR Reykjavik",
    # --- Belarus Premier League (111) ---
    "Borisfen 2": "Borisfen Mogilev Youth",
    "SDUSHOR Minsk": "RCOP-SDUSHOR",
    # --- China CBA (31) ---
    "Zhejiang Guangsha": "Zhejiang Golden Bulls",
    # --- Poland Energa Basket Liga (72) ---
    "Ostrow Wielkopolski": "Stal Ostrów Wielkopolski",
    "Dabrowa Gornicza": "MKS Dąbrowa Górnicza",
    "Zielona Gora": "Enea Zastal Zielona Góra",
    "Torun": "Twarde Pierniki Toruń",
    "Gornik Walbrzych": "Górnik Trans.eu Walbrzych",
    # --- Puerto Rico BSN (76) ---
    # Note: Leaderboard now stores API-native names. No overrides needed.
    # --- Europe ABA League (198) ---
    "FMP Beograd": "FMP SoccerBet",
    "Spartak Subotica": "Spartak Office Shoes",
    "Mega Basket": "Mega MIS",
    # --- Europe BNXT League (368) ---
    "Zwolle": "Landstede Hammers",
    # --- Europe Euroleague (120) ---
    "Crvena Zvezda Meridianbet": "Crvena Zvezda Belgrade",
    "Olimpia Milano": "EA7 Emporio Armani Milan",
    "Valencia": "Valencia Basket",
    "Virtus Bologna": "Virtus Segafredo Bologna",
    "Virtus Bologna": "Virtus Segafredo Bologna",
    "Bayern": "FC Bayern Munich",
    "Baskonia": "Baskonia Vitoria-Gasteiz",
    "Maccabi Tel Aviv": "Maccabi Playtika Tel Aviv",
    "Panathinaikos":  "Panathinaikos Athens",
    "Barcelona": "FC Barcelona",
    "Olympiacos": "Olympiacos Piraeus",
    # --- USA NBA W (13) ---
    "Golden State Valkyries W": "Golden State Valkyries",
    "Las Vegas Aces W": "Las Vegas Aces",
    "Phoenix Mercury W": "Phoenix Mercury",
    # --- Lithuania NKL (61) ---
    "Neptunas 2": "Klaipėdos Neptūnas-Akvaservis",
    "Zalgiris Kaunas 2": "Zalgiris Kaunas II",
    # --- Romania Divizia A (78) ---
    "Municipal Galati": "CSM Galati",
    "CSM Oradea": "CSM CSU Oradea",
    # --- Poland 1 Liga (71) ---
    "R. Rzeszow": "Resovia",
    "Lancut": "Solvera Sokół Łańcut",
    "Poli. Opolska": "Weegree AZS Politechnika Opolska",
    "Starogard Gdanski": "SKS Starogard Gdanski",
    # --- ABA League 2 (203) ---
    "Siroki Brijeg": "Široki TT Kabeli",
    "Helios Domzale": "Kansai Helios Domžale",
    # --- Japan B League (56) ---
    "Hiroshima D.": "Hiroshima Dragonflies",
    # --- Denmark Basketligaen (34) ---
    "Herlev Wolfpack": "BMS Herlev",
    # --- Belgium Pro Basketball League (374) ---
    "Antwerp Giants":              "Windrose Giants Antwerp",
    "Spirou Charleroi":            "Spirou Basket",
    "Oostende":                    "Filou Oostende",
    "Mechelen":                    "Kangoeroes",
    "Okapi Aalst":                 "Okapi Aalstar",
    "Limburg":                     "Limburg United",
    "Kortrijk":                    "Kortrijk Spurs",
    "Mons-Hainaut":                "Union Mons-Hainaut",
    "Liege":                       "Liege Basket",
    # --- Netherlands DBL (65) ---
    "Den Helder":                  "Den Helder Suns",
    "Zwolle":                      "Landstede Hammers",
    "Leiden":                      "ZZ Leiden",
    "BAL Weert":                   "PrismaWorx BAL",
    "Rotterdam":                   "Rotterdam City Basketball",
    "Den Bosch":                   "Heroes Den Bosch",
    # --- Argentina Liga A (18) ---
    "Ferro": "Ferro Carril Oeste",
    "Obera TC": "Obera Tennis Club",
    # --- Italy Serie A2 (242) ---
    "Urania Milano": "Wegreenit Urania Milano",
    "Blu Basket Bergamo": "Gruppo Mascio Bergamo",
    "Basket Torino": "Reale Mutua Torino",
    "Pesaro": "Victoria Libertas Pesaro",
    # --- Turkey TBL (102) ---
    "Konya BBSK": "Konyaspor",
    "CO Basket": "Cedi Osman Spor Kulubu",
    "Ankara Kolejliler": "TED Kolejliler",
    "Kipas Istiklal": "Kahramanmaras Belediye",
    "Fenerbahce 2": "Fenerbahce II",
    # --- China CBA (31) ---
    "Zhejiang Chouzhou": "Zhejiang Golden Bulls",
    # --- Czech NBL (32) ---
    "Slavia Prague": "Slavia Praha",
    # --- Europe Euroleague (120) ---
    "Partizan Mozzart Bet": "Partizan Belgrade",
    "Lyon-Villeurbanne": "LDLC ASVEL",
    # --- Slovakia Extraliga (87) ---
    "Levice": "Levickí Patrioti",
    "Spisski Rytieri": "Spišskí Rytieri",
    # --- Bulgaria NBL (113) ---
    "Lok. Plovdiv": "Lokomotiv Plovdiv",
    # --- Saturday April 11 Additions ---
    "Polonia Warszawa": "KKS Polonia Warszawa",
    "Spojnia Stargard": "PGE Spójnia Stargard",
    "KK Bosna": "Bosna Royal",
    "Igokea": "Igokea m:tel",
    "Basket Zaragoza": "Casademont Zaragoza",
    "Forca Lleida": "Hiopos Lleida",
    "Jena": "Science City Jena",
    "Wurzburg": "Würzburg Baskets",
    "Spirou Charleroi": "Spirou Basket",
    "BAL Weert": "PrismaWorx BAL",
    "Oostende": "Filou Oostende",
    "Mechelen": "Kangoeroes",
    "Belfius Mons": "Union Mons-Hainaut",
    "Zwolle": "Landstede Hammers",
    "Mladost Zemun": "Mladost MaxBet",
    "Sloga": "Sloga Kraljevo",
    "Vojvodina Novi Sad": "Vojvodina MTS",
    "Vrsac": "Vršac Meridianbet",
    "La Roche W": "Roche Vendée",
    "Landes W": "Basket Landes",
    "Jonava": "Jonavos CBet",
    "Reggiana": "UNAHOTELS Reggio Emilia",
    "Cremona": "Vanoli Cremona",
    "Kaposvari": "Kaposvari KK",
    "Atomeromu Paks": "Atomeromu SE",
    "Kecskemeti TE": "KTE Duna Aszfalt",
    "Kormend": "Egis Kormend",
    "Szedeak": "SZTE-Szedeák",
    "Srsni Pisek": "Sršni Písek",
    "Nymburk": "ERA Nymburk",
    "USK Prague": "USK Praha",
    "Grodno GrSU": "Grodno-GrGU",
    "Gomel": "GOCOR-Soj Gomel",
    "Borisfen 2": "Borisfen Mogilev Youth",
    "Rubon II": "Rubon Vitebsk II",
    "Obradoiro CAB": "Monbus Obradoiro",
    "Estela": "Grupo Alega Cantabria",
    "Artland": "Artland Dragons",
    "Tubingen": "Tigers Tübingen",
    "Paderborn": "Baskets Paderborn",
    "Crailsheim Merlins": "HAKRO Merlins Crailsheim",
    "Donji Vakuf - Promo": "Promo Donji Vakuf",
    "Mrkonjic Grad": "Mladost Mrkonjic Grad",
    "Sol Girones Bisbal": "Bisbal Basquet",
    "Huesca": "Levitec Huesca",
    "Gandia": "Basquet Gandia",
    "CBC Valladolid": "Real Valladolid",
    "St. Polten": "SKN St. Pölten Basketball",
    "BBC Nord": "Eisenstadt Dragonz",
    # --- Sunday April 12 & 13 Additions ---
    "Frankfurt": "Fraport Skyliners",
    "Heidelberg": "MLP Academics Heidelberg",
    "Legia": "Legia Warszawa",
    "Gornik Walbrzych": "Górnik Trans.eu Walbrzych",
    "Flammes Carolo W": "Charleville-Mézières",
    "ESB Villeneuve W": "Villeneuve d'Ascq",
    "Gargzdai": "Gargždai Basketball",
    "JL Bourg": "Bourg-en-Bresse",
    "Monaco": "AS Monaco",
    "Sassari": "Dinamo BDS Sassari",
    "Tortona": "Bertram Tortona",
    "Trento": "Dolomiti Energia Trentino",
    "Basket Napoli": "Napolibasket",
    "Treviso": "Nutribullet Treviso",
    "Bremerhaven": "Eisbären Bremerhaven",
    "Nurnberger": "Nurnberg Falcons BC",
    "Logrono": "Logro Basket",
    "Iraurgi SB": "Biele ISB",
    "Jaen": "Jaen CB",
    "Studentski Centar": "SC Derby",
    "Mega Basket": "Mega MIS",
    "Cluj-Napoca": "U-BT Cluj Napoca",
}

def get_today_str(date_str=None):
    if date_str:
        return date_str
    return datetime.now(ET_TZ).strftime("%Y-%m-%d")


def load_json(path):
    if not os.path.exists(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def save_json(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2)


# ------------------------------------------------------------------
# MATCH CENTER HELPERS (Parity with Football)
# ------------------------------------------------------------------



# ------------------------------------------------------------------
# STEP 1: FETCH TODAY'S FIXTURES
# ------------------------------------------------------------------

def fetch_today_fixtures(date_str, refresh=False):
    """
    Returns all games for today from api-basketball.com.
    Uses cached file if available and refresh=False.
    """
    cache_path = f"data/api_basketball_today_{date_str}.json"

    if not refresh and os.path.exists(cache_path):
        print(f"  Using cached fixtures: {cache_path}")
        data = load_json(cache_path)
        return data.get("leagues_summary", [])

    print(f"  Fetching fixtures for {date_str} from api-basketball.com...")
    try:
        r = requests.get(
            f"{BASE_URL}/games",
            headers=HEADERS,
            params={"date": date_str},
            timeout=15,
        )
        all_games = r.json().get("response", [])
        total = r.json().get("results", 0)
        print(f"  Got {total} games.")
    except Exception as e:
        print(f"  ERROR fetching fixtures: {e}")
        return []

    from collections import defaultdict
    by_league = defaultdict(list)
    for game in all_games:
        league = game.get("league", {})
        lid    = league.get("id")
        lname  = league.get("name", "Unknown")
        country = game.get("country", {}).get("name", "")
        season = league.get("season")
        home = game.get("teams", {}).get("home", {}).get("name", "?")
        away = game.get("teams", {}).get("away", {}).get("name", "?")
        hs = game.get("scores", {}).get("home", {}).get("total")
        as_ = game.get("scores", {}).get("away", {}).get("total")
        home_id = game.get("teams", {}).get("home", {}).get("id")
        away_id = game.get("teams", {}).get("away", {}).get("id")
        by_league[(lid, lname, country, season)].append({
            "home": home, "away": away,
            "home_id": home_id, "away_id": away_id,
            "home_score": hs, "away_score": as_,
            "time": game.get("date", "")[:16].replace("T", " "),
            "status": game.get("status", {}).get("long", "Scheduled"),
            "stage": game.get("stage") or game.get("week") or "",
        })

    leagues_summary = [
        {
            "league_id": lid, "league_name": lname,
            "country": country, "season": season,
            "game_count": len(games), "games": games,
        }
        for (lid, lname, country, season), games in
        sorted(by_league.items(), key=lambda x: x[0][1])
    ]

    out = {"date": date_str, "total_games": total, "leagues_summary": leagues_summary}
    save_json(cache_path, out)
    return leagues_summary


def get_yesterday_teams(date_str, refresh=False):
    """
    Returns a set of team names and IDs that played on the day before date_str.
    """
    try:
        target_date = datetime.strptime(date_str, "%Y-%m-%d")
        yesterday_date = target_date - timedelta(days=1)
        yesterday_str = yesterday_date.strftime("%Y-%m-%d")
        
        leagues_summary = fetch_today_fixtures(yesterday_str, refresh=False) # Always cache yesterday
        
        played_yesterday = set()
        if not leagues_summary:
            return played_yesterday
            
        for league in leagues_summary:
            for game in league.get("games", []):
                if game.get("home_id"): played_yesterday.add(game["home_id"])
                if game.get("away_id"): played_yesterday.add(game["away_id"])
                if game.get("home"): played_yesterday.add(game["home"])
                if game.get("away"): played_yesterday.add(game["away"])
                
        return played_yesterday
    except Exception as e:
        print(f"  Warning: Fatigue schedule fetch failed: {e}")
        return set()

# ------------------------------------------------------------------
# STEP 2: LOAD OR CALIBRATE CONFIG
# ------------------------------------------------------------------

def get_or_calibrate_config(league_id, league_name, auto_calibrate=True):
    """
    Load config for league_id. Auto-calibrate if missing.
    Returns (config_path, config_dict) or (None, None) if unavailable.
    """
    config_path = f"configs/leagues/{league_id}.json"

    if os.path.exists(config_path):
        cfg = load_json(config_path)
        if cfg and cfg.get("name"):
            return config_path, cfg
        else:
            print(f"    WARNING: Legacy config {league_id}.json is missing 'name'. Deleting to force fresh auto-calibration.")
            try:
                os.remove(config_path)
            except Exception as e:
                print(f"      Failed to delete corrupted config: {e}")

    if auto_calibrate:
        print(f"    No config found for league {league_id}.")
        print(f"    WARNING: LIVE API Calibration is permanently disabled. Please run calibrate_from_local.py to securely generate baselines.")

    return None, None


# ------------------------------------------------------------------
# STEP 3: LOAD OR FETCH TEAM STATS
# ------------------------------------------------------------------

def get_advanced_stats(league_id, season=None):
    """Load cached [ADVANCED] matrix if available."""
    from fetch_universal_bball_stats import attach_prior_season_stats
    matrix_path = f"data/bball_stats_{league_id}_adv.json"
    if os.path.exists(matrix_path):
        data = load_json(matrix_path)
        # Verify it's a REAL advanced matrix, not an SRS fallback
        if data.get("note") == "Insufficient box-score coverage; using SRS fallback":
            return None
        teams_list = data.get("teams", [])
        if teams_list:
            teams = {t["team_name"]: t for t in teams_list}
            return attach_prior_season_stats(teams, league_id, season)
    return None

def _load_teams_from_file(path):
    """Helper: load teams from a stats file, returning dict or {} on failure."""
    data = load_json(path)
    if not data:
        return {}
    # Both formats: {teams: [...]} list form and {team_name: {...}} dict form
    teams_raw = data.get("teams", data)
    if isinstance(teams_raw, list):
        return {t["team_name"]: t for t in teams_raw if t.get("team_name")}
    if isinstance(teams_raw, dict):
        return teams_raw
    return {}

def get_srs_stats(league_id, season, refresh=False):
    """
    Load cached [  SRS   ] matrix or fetch fallback from API.
    Priority: _srs.json -> srs_stats_N.json -> bball_stats_N.json -> season file -> API fetch
    Seamlessly attaches prior season true-talent data for early-season teams (< 8 games).
    """
    from fetch_universal_bball_stats import get_current_season, fetch_stats, attach_prior_season_stats

    # 1. New proprietary SRS matrix
    matrix_path = f"data/bball_stats_{league_id}_srs.json"
    if os.path.exists(matrix_path):
        teams = _load_teams_from_file(matrix_path)
        if teams:
            return attach_prior_season_stats(teams, league_id, season)

    # 2. Legacy srs_stats file (generated by older pipeline)
    srs_legacy_path = f"data/srs_stats_{league_id}.json"
    if os.path.exists(srs_legacy_path):
        teams = _load_teams_from_file(srs_legacy_path)
        if teams:
            return attach_prior_season_stats(teams, league_id, season)

    # 3. Old non-suffixed bball_stats file
    old_path = f"data/bball_stats_{league_id}.json"
    if not refresh and os.path.exists(old_path):
        teams = _load_teams_from_file(old_path)
        if teams:
            return attach_prior_season_stats(teams, league_id, season)

    # 4. API season-specific files
    if not season:
        season = get_current_season(league_id)

    exact_path = f"data/bball_stats_{league_id}_{season}.json"
    if not refresh and os.path.exists(exact_path):
        teams = _load_teams_from_file(exact_path)
        if teams:
            return attach_prior_season_stats(teams, league_id, season)

    if not refresh:
        existing = sorted(glob.glob(f"data/bball_stats_{league_id}_*.json"), reverse=True)
        for p in existing:
            teams = _load_teams_from_file(p)
            if teams:
                return attach_prior_season_stats(teams, league_id, season)

    try:
        teams = fetch_stats(league_id, season=season, verbose=False)
        return attach_prior_season_stats(teams, league_id, season)
    except Exception as e:
        print(f"    Stats fetch failed: {e}")
        return {}


# ------------------------------------------------------------------
# STEP 4: FUZZY TEAM MATCHING
# ------------------------------------------------------------------

def find_team(name, stats_dict):
    """
    Case-insensitive + partial fuzzy match of team name against stats dict keys.
    Returns (matched_key, stats) or (None, None).
    """
    if not name or not stats_dict:
        return None, None

    original_name = name
    name = TEAM_NAME_OVERRIDES.get(name, name)

    # First try with the override name
    best_key, stats = _fuzzy_match(name, stats_dict)
    if best_key:
        return best_key, stats

    # Fallback to the original name if the override broke the match
    if name != original_name:
        return _fuzzy_match(original_name, stats_dict)
        
    return None, None

def _fuzzy_match(name, stats_dict):
    name_lower = name.lower().strip()

    # Exact match
    if name in stats_dict:
        return name, stats_dict[name]

    # Case-insensitive
    for k in stats_dict:
        if k.lower() == name_lower:
            return k, stats_dict[k]

    # Partial: name contains key or key contains name
    for k in stats_dict:
        k_lower = k.lower()
        if k_lower in name_lower or name_lower in k_lower:
            return k, stats_dict[k]

    # High character overlap via difflib (Safer than single word overlaps)
    import difflib
    best_key, best_score = None, 0.0
    for k in stats_dict:
        similarity = difflib.SequenceMatcher(None, name_lower, k.lower()).ratio()
        if similarity > best_score:
            best_key, best_score = k, similarity
            
    if best_score >= 0.85:
        return best_key, stats_dict[best_key]

    return None, None
    
def global_find_team(name):
    """
    Last resort fallback: Search ALL available bball_stats_*.json files for this team.
    Useful for teams that play in multiple leagues (e.g. Cedevita Olimpija in Slovenia vs ABA).
    """
    search_pattern = "data/bball_stats_*_adv.json"
    files = glob.glob(search_pattern)
    
    # Try exact overrides first
    canonical_name = TEAM_NAME_OVERRIDES.get(name, name)
    
    for fpath in files:
        try:
            with open(fpath, encoding="utf-8") as f:
                data = json.load(f)
                teams = {t["team_name"]: t for t in data.get("teams", [])}
                
                # Try exact canonical
                if canonical_name in teams:
                    return teams[canonical_name], fpath
                
                # Try fuzzy in this file
                best_k, best_s = find_team(name, teams)
                if best_k:
                    return best_s, fpath
        except: continue
        
    return None, None


# ------------------------------------------------------------------
# STEP 5: PREDICT ONE GAME
# ------------------------------------------------------------------

def calculate_win_prob(spread, std_dev=12.0):
    """Convert a point spread to a win probability using a normal distribution."""
    # probability = norm.cdf(spread / std_dev)
    # Using a simple approximation if scipy is not available, but norm.cdf is better
    return norm.cdf(spread / std_dev)

def predict_game(away_name, home_name, away_id, home_id, team_stats, config, config_path, mode, trace, yesterday_teams=None, ghost_injuries=None):
    """
    Run the UniversalBasketballEngine for a single matchup.
    Returns engine result dict or None if teams not found.
    """
    from core.basketball_engine import UniversalBasketballEngine

    away_key, sA = find_team(away_name, team_stats)
    home_key, sH = find_team(home_name, team_stats)

    # GLOBAL FALLBACK
    if not sA:
        sA, src = global_find_team(away_name)
        if sA:
            sA = dict(sA)
            sA["source"] = f"GLOBAL ({os.path.basename(src)})"
    if not sH:
        sH, src = global_find_team(home_name)
        if sH:
            sH = dict(sH)
            sH["source"] = f"GLOBAL ({os.path.basename(src)})"

    if not sA or not sH:
        missing = []
        if not sA: missing.append(away_name)
        if not sH: missing.append(home_name)
        return None, f"Team stats not found: {', '.join(missing)}"

    # Build game_data in the format the engine expects
    cfg = config
    config_pace = cfg.get("pace_pivot", 76)

    MIN_GAMES_TRUST = 8
    a_gp = sA.get("games_played", sA.get("games", 0))
    h_gp = sH.get("games_played", sH.get("games", 0))

    prev_a = sA.get("previous_season")
    prev_h = sH.get("previous_season")
    a_prev_gp = prev_a.get("games_played", prev_a.get("games", 0)) if prev_a else 0
    h_prev_gp = prev_h.get("games_played", prev_h.get("games", 0)) if prev_h else 0

    # STRICT GUARD: Require either 2+ current games OR a valid prior season baseline (>= 3 games or SRS rating)
    a_has_baseline = (a_gp >= 2) or (prev_a and (a_prev_gp >= 3 or prev_a.get("srs_rating") is not None))
    h_has_baseline = (h_gp >= 2) or (prev_h and (h_prev_gp >= 3 or prev_h.get("srs_rating") is not None))

    if not a_has_baseline or not h_has_baseline:
        return None, f"Insufficient games played & no prior season baseline. {away_name} (curr={a_gp}, prev={a_prev_gp}), {home_name} (curr={h_gp}, prev={h_prev_gp}). Skipping."

    eff_pivot = cfg.get("eff_pivot", 108.0)

    # Dynamic Bayesian & Prior-Season Smoothing
    def smooth_team_ratings(team_s, eff_pivot, config_pace, name):
        gp = team_s.get("games_played", team_s.get("games", 0))
        prev_s = team_s.get("previous_season")
        
        if prev_s and gp < MIN_GAMES_TRUST:
            # Shift smoothly from prior to current over MIN_GAMES_TRUST (8) games
            w_curr = max(0.0, min(1.0, gp / float(MIN_GAMES_TRUST)))
            w_prev = 1.0 - w_curr
            
            raw_off = team_s.get("adj_off", eff_pivot)
            raw_def = team_s.get("adj_def", eff_pivot)
            raw_t   = team_s.get("adj_t", config_pace)
            
            prev_off = prev_s.get("adj_off", eff_pivot)
            prev_def = prev_s.get("adj_def", eff_pivot)
            prev_t   = prev_s.get("adj_t", config_pace)
            
            team_s["adj_off"] = round((raw_off * w_curr) + (prev_off * w_prev), 1)
            team_s["adj_def"] = round((raw_def * w_curr) + (prev_def * w_prev), 1)
            team_s["adj_t"]   = round((raw_t   * w_curr) + (prev_t   * w_prev), 1)
            team_s["prior_blended"] = True
            print(f"    ⭐ PRIOR BLEND: {name} (curr {gp}g, prior {prev_s.get('games_played', prev_s.get('games', '?'))}g) -> Off={team_s['adj_off']}, Def={team_s['adj_def']}, Pace={team_s['adj_t']}")
        elif gp < MIN_GAMES_TRUST:
            # Fallback to standard Bayesian blend toward generic league default
            weight_team = gp / float(MIN_GAMES_TRUST)
            weight_league = 1.0 - weight_team
            team_s["adj_off"] = round((team_s.get("adj_off", eff_pivot) * weight_team) + (eff_pivot * weight_league), 1)
            team_s["adj_def"] = round((team_s.get("adj_def", eff_pivot) * weight_team) + (eff_pivot * weight_league), 1)
            team_s["adj_t"]   = round((team_s.get("adj_t", config_pace) * weight_team) + (config_pace * weight_league), 1)
            print(f"    ⚠ SMALL SAMPLE: {name} ({gp} games) — Bayesian blending toward league average")

    if a_gp < MIN_GAMES_TRUST:
        smooth_team_ratings(sA, eff_pivot, config_pace, away_name)

    if h_gp < MIN_GAMES_TRUST:
        smooth_team_ratings(sH, eff_pivot, config_pace, home_name)

    raw_pace = (sA.get("adj_t", config_pace) + sH.get("adj_t", config_pace)) / 2

    # SANITY CHECK: override adj_t if it deviates wildly from config pace_pivot
    if abs(raw_pace - config_pace) > 20:
        print(f"    ⚠ PACE OVERRIDE: adj_t ({raw_pace:.1f}) deviates from pace_pivot ({config_pace}). Using config value.")
        raw_pace = config_pace

    # FIX 2: KenPom-style crossmatch efficiency for ALL leagues
    lg_avg_eff = cfg.get("eff_pivot", 108.0)
    a_off = sA.get("adj_off", lg_avg_eff)
    a_def = sA.get("adj_def", lg_avg_eff)
    h_off = sH.get("adj_off", lg_avg_eff)
    h_def = sH.get("adj_def", lg_avg_eff)

    # v4.2 Fix: Additive Model (eliminates exponential overshoot)
    a_off_delta = a_off - lg_avg_eff
    h_def_delta = h_def - lg_avg_eff
    h_off_delta = h_off - lg_avg_eff
    a_def_delta = a_def - lg_avg_eff

    exp_a_eff = lg_avg_eff + a_off_delta + h_def_delta
    exp_h_eff = lg_avg_eff + h_off_delta + a_def_delta
    crossmatch_eff = (exp_a_eff + exp_h_eff) / 2

    # FIX 4 (REVISED): Multiplicative KenPom spread perfectly constrained by Game Pace & Home Court Advantage
    raw_spread_eff = exp_h_eff - exp_a_eff
    hca_spread = cfg.get("hca_spread_bump", 2.5) 
    spread_est = (raw_spread_eff * (raw_pace / 100)) + hca_spread

    is_b2b_home = False
    is_b2b_away = False
    if yesterday_teams is not None:
        is_b2b_home = (home_id in yesterday_teams) or (home_name in yesterday_teams)
        is_b2b_away = (away_id in yesterday_teams) or (away_name in yesterday_teams)

    game_data = {
        "team":       away_name,
        "opponent":   home_name,
        "statsA":     sA,
        "statsH":     sH,
        "pace_adjustment":      raw_pace,
        "efficiency_adjustment": crossmatch_eff,
        "projected_spread": abs(spread_est),
        "market_total": None,
        "is_neutral": False,
        "is_b2b_home": is_b2b_home,
        "is_b2b_away": is_b2b_away,
    }

    try:
        engine = UniversalBasketballEngine(config_path, mode=mode)
        engine.trace_enabled = trace
        
        # Merge ghost injuries
        game_injuries = []
        if ghost_injuries:
            game_injuries.extend(ghost_injuries.get(away_name, []))
            game_injuries.extend(ghost_injuries.get(home_name, []))
            
        result = engine.calculate_total(game_data, injury_notes=game_injuries)
        # FIX 4: Spread uses both offense and defense
        spr = spread_est  # Already computed above with crossmatch formula
        model_total = result.get("final_model_total", 0.0)

        # HARD CEILING: Cap non-NBA model totals at 250 as a safety net
        if model_total > 250 and cfg.get("name") != "NBA":
            print(f"    ⚠ CEILING CAP: Inflated projection {model_total:.1f} -> 250.0")
            model_total = 250.0
            result["final_model_total"] = model_total
        
        xpts_h = (model_total / 2) + (spr / 2)
        xpts_a = (model_total / 2) - (spr / 2)
        result["xpts_h"] = round(xpts_h, 1)
        result["xpts_a"] = round(xpts_a, 1)

        # FIX 8: Configurable win probability std_dev
        win_std = cfg.get("win_prob_std_dev", 12.0)
        p_home = calculate_win_prob(spr, std_dev=win_std)
        p_away = 1.0 - p_home
        
        result["probs_1x2"] = {
            "home": round(p_home * 100, 1),
            "away": round(p_away * 100, 1)
        }
        result["predicted_result"] = "HOME" if spr > 0 else "AWAY"
        
        return result, None
    except Exception as e:
        return None, str(e)


# ------------------------------------------------------------------
# MAIN
# ------------------------------------------------------------------

def main():
    parser = argparse.ArgumentParser(description="Universal Daily Basketball Predictions")
    parser.add_argument("--date",       help="Date YYYY-MM-DD (default: today)")
    parser.add_argument("--league_id",  type=int, help="Only run one league")
    parser.add_argument("--mode",       choices=["safe", "full"], default="safe")
    parser.add_argument("--min_games",  type=int, default=1,
                        help="Skip leagues with fewer than this many games today")
    parser.add_argument("--refresh",    action="store_true", help="Re-fetch fixtures from API")
    parser.add_argument("--trace",      action="store_true", help="Show engine math trace")
    parser.add_argument("--no_calibrate", action="store_true",
                        help="Skip auto-calibration (use existing configs only)")
    parser.add_argument("--match_center", action="store_true", default=True,
                        help="Enrich with H2H, Standings, etc (costly API calls)")
    parser.add_argument("--no_match_center", action="store_false", dest="match_center",
                        help="Disable Match Center enrichment to save API credits")
    parser.add_argument("--validate",   action="store_true",
                        help="Print top 5 highest/lowest totals as sanity check")
    args = parser.parse_args()

    date_str = get_today_str(args.date)

    print("\n" + "=" * 70)
    print(f"  UNIVERSAL BASKETBALL PREDICTIONS | {date_str} | {args.mode.upper()}")
    print("=" * 70)

    # Step 1: get fixtures
    leagues = fetch_today_fixtures(date_str, refresh=args.refresh)
    if not leagues:
        print("  No fixtures found. Check API key or try --refresh.")
        return

    # Step 1.5: get yesterday's teams for Back-to-Back fatigue check
    yesterday_fatigued_teams = get_yesterday_teams(date_str, refresh=False)

    # Filter — always exclude dedicated-model leagues
    leagues = [
        l for l in leagues
        if l["league_id"] not in EXCLUDED_LEAGUE_IDS
    ]
    if args.league_id:
        leagues = [l for l in leagues if l["league_id"] == args.league_id]
    if args.min_games > 1:
        leagues = [l for l in leagues if l["game_count"] >= args.min_games]

    print(f"  Running predictions for {len(leagues)} league(s)...\n")
    total_games_today = sum(l.get("game_count", 0) for l in leagues)

    all_predictions = []
    total_predicted = 0
    total_skipped   = 0
    skipped_issues  = []
    
    # Load Global M.B.E.T Array
    mbet_matrix = load_json("configs/league_edge_thresholds.json") or {}
    
    # Load Leaderboard for Confidence Scoring snapshot
    print(f"  Loading leaderboard for runtime confidence scoring...")
    lb_index = load_leaderboard()

    for league_entry in leagues:
        lid      = league_entry["league_id"]
        lname    = league_entry["league_name"]
        country  = league_entry.get("country", "")
        season   = league_entry.get("season")
        games    = league_entry["games"]

        # Skip already-finished games if they have scores
        upcoming = [g for g in games if g.get("status") not in
                    ("Game Finished", "Final", "AOT")]
        if not upcoming:
            upcoming = games  # Show all if all finished (useful for backtesting)

        print(f"  [{lid}] {lname} ({country}) — {len(games)} game(s)")

        # Step 2: config
        config_path, config = get_or_calibrate_config(
            lid, lname, auto_calibrate=not args.no_calibrate
        )
        if not config_path:
            msg = f"[{lid}] {lname} - SKIP: no config available"
            print(f"    SKIP -- no config available\n")
            skipped_issues.append(msg)
            total_skipped += len(games)
            continue

        # Step 3: team stats
        stats_srs = get_srs_stats(lid, season, refresh=args.refresh)
        stats_adv = get_advanced_stats(lid)
        
        ghost_injuries = {}
        try:
            with open(f"data/ghost_injuries_{lid}.json", "r", encoding="utf-8") as f:
                ghost_injuries = json.load(f)
        except:
            pass
            
        if not stats_srs:
            msg = f"[{lid}] {lname} - SKIP: no team stats available"
            print(f"    SKIP — no team stats available\n")
            skipped_issues.append(msg)
            total_skipped += len(games)
            continue

        # Step 4: league standings
        # Removed API standings fetch

        # Step 5: pre-fetch league recents (saves calls vs per-team)
        # Removed API league recents fetch

        # Step 6: predict each game
        for game in games:
            away = game["away"]
            home = game["home"]
            status = game.get("status", "")
            stage = game.get("stage", "")

            # Extract HH:MM kickoff time from fixture date (e.g. "2026-08-24 18:30" → "18:30")
            raw_time = game.get("time", "") or ""
            kickoff_time = raw_time.split(" ")[1] if " " in raw_time else None

            away_id = game.get("away_id")
            home_id = game.get("home_id")

            best_pass = None

            # PASS 1: Try ADVANCED Model first if matrix exists
            if stats_adv:
                result_adv, err_adv = predict_game(
                    away, home, away_id, home_id, stats_adv, config, config_path, args.mode, args.trace, yesterday_fatigued_teams, ghost_injuries
                )
                if not err_adv:
                    best_pass = (result_adv, "[ADVANCED]", stats_adv)

            # PASS 2: Fallback to SRS if ADVANCED failed or doesn't exist
            if not best_pass:
                result_srs, err_srs = predict_game(
                    away, home, away_id, home_id, stats_srs, config, config_path, args.mode, args.trace, yesterday_fatigued_teams, ghost_injuries
                )
                if not err_srs:
                    best_pass = (result_srs, "[  SRS   ]", stats_srs)
                else:
                    msg = f"[{lid}] {lname} - {away} @ {home} - SKIP: {err_srs}"
                    print(f"    {away} @ {home}  -- SKIP ({err_srs})")
                    skipped_issues.append(msg)
                    total_skipped += 1
                    continue
                    
            passes = [best_pass]
                
            for res, matrix_type, active_stats in passes:
                model_total = res.get("final_model_total", 0.0)
                market      = res.get("market_total")
                edge        = res.get("edge")
                decision    = res.get("decision", "MODEL ONLY")
                confidence  = res.get("confidence", "-")
                side        = res.get("side", "-")
                
                # Post-Engine M.B.E.T Filter Enforcement
                mbet = mbet_matrix.get(str(lid), {}).get("recommended_minimum_edge", 4.0)
                if edge is not None and market not in (145.5, 230.0):
                    if edge >= mbet:
                        decision = f"PLAY {side}"
                        confidence = "HIGH" if edge >= mbet + 1.5 else "SOLID"
                    else:
                        decision = "PASS"
                        confidence = "MBET FILTER"

                # Format output line
                if market and market not in (145.5, 230.0):
                    mkt_str = f"Mkt:{market:.1f}"
                    edge_str = f"Edge:{edge:+.1f} {side} [{confidence}] -> {decision}"
                else:
                    mkt_str = "Mkt:N/A"
                    edge_str = "MODEL ONLY (no line)"

                score_str = ""
                if game.get("home_score") is not None:
                    score_str = f"  Final: {game['away_score']}-{game['home_score']}"

                print(f"    {matrix_type} {away:24} @ {home:24}")
                print(f"      Model:{model_total:.1f}  {mkt_str}  {edge_str}{score_str} | MBET: {mbet}")

                if args.trace:
                    for t in res.get("trace", []):
                        print(f"        > {t}")

                # Optimized Match Center Data
                h2h = []
                recentH = []
                recentA = []
                league_standings_data = None
                
                if args.match_center:
                    offline_data = compile_offline_match_center(lid, lname, home, away)
                    h2h = offline_data["h2h"]
                    recentH = offline_data["recentH"]
                    recentA = offline_data["recentA"]
                    league_standings_data = offline_data["full_standings"]
                
                _, sA = find_team(away, active_stats)
                _, sH = find_team(home, active_stats)

                # Snapshot Confidence Score at Runtime
                DEFAULT_MAE = 12.0
                xpts_h = res.get("xpts_h", model_total / 2)
                xpts_a = res.get("xpts_a", model_total / 2)
                spread = abs(xpts_h - xpts_a)
                
                vol_h = sH.get("std_dev_totals", DEFAULT_MAE) if sH else DEFAULT_MAE
                vol_a = sA.get("std_dev_totals", DEFAULT_MAE) if sA else DEFAULT_MAE
                
                mae_h, bias_h, graded_h, hr_h, hr_total_h, _ = get_team_stats(home, lid, lb_index)
                mae_a, bias_a, graded_a, hr_a, hr_total_a, _ = get_team_stats(away, lid, lb_index)
                
                conf_input = {
                    "vol_a": vol_a, "vol_b": vol_h,
                    "mae_a": mae_a, "mae_b": mae_h,
                    "bias_a": bias_a, "bias_b": bias_h,
                    "spread": spread,
                    "hit_rate_a": hr_a, "hit_rate_b": hr_h,
                    "hit_rate_games_a": hr_total_a, "hit_rate_games_b": hr_total_h
                }
                conf_res = compute_confidence(conf_input)

                # Clash of Inefficient Detection
                is_clash = False
                clash_trigger = ""
                if sH and sA:
                    eff_pivot = config.get("eff_pivot", 108.0)
                    h_off, h_def = sH.get("adj_off"), sH.get("adj_def")
                    a_off, a_def = sA.get("adj_off"), sA.get("adj_def")
                    if h_off is not None and h_def is not None and a_off is not None and a_def is not None:
                        if h_off < eff_pivot and a_off < eff_pivot and h_def > eff_pivot and a_def > eff_pivot:
                            is_clash = True
                            clash_mkt = market if (market and market not in (145.5, 230.0)) else None
                            if clash_mkt is not None and (model_total - clash_mkt) >= 7.0:
                                clash_trigger = "SHARP OVER"
                            else:
                                clash_trigger = "CLASH"

                # Build record
                all_predictions.append({
                    "is_clash":      is_clash,
                    "clash_trigger": clash_trigger,
                    "league_id":    lid,
                    "league":       lname,
                    "country":      country,
                    "date":         date_str,
                    "time":         kickoff_time,
                    "away_team":    away,
                    "home_team":    home,
                    "status":       status,
                    "stage":        stage,
                    "model_total":  model_total,
                    "xpts_h":       round(res.get("xpts_h", 0), 1),
                    "xpts_a":       round(res.get("xpts_a", 0), 1),
                    "probs_1x2":    res.get("probs_1x2", {}),
                    "predicted_result": res.get("predicted_result"),
                    "home_source":  sH.get("source", "SRS") if sH else "SRS",
                    "away_source":  sA.get("source", "SRS") if sA else "SRS",
                    "home_team_volatility": sH.get("std_dev_totals", None) if sH else None,
                    "away_team_volatility": sA.get("std_dev_totals", None) if sA else None,
                    "market_total": market if (market and market not in (145.5, 230.0)) else None,
                    "edge":         edge if (market and market not in (145.5, 230.0)) else None,
                    "side":         side if (market and market not in (145.5, 230.0)) else None,
                    "decision":     decision if (market and market not in (145.5, 230.0)) else "MODEL ONLY",
                    "confidence":   confidence,
                    "confidence_score_band": conf_res["band"]["label"].strip(),
                    "confidence_score": conf_res["confidence_score"],
                    "mae_h": mae_h,
                    "mae_a": mae_a,
                    "bias_h": bias_h,
                    "bias_a": bias_a,
                    "graded_h": graded_h,
                    "graded_a": graded_a,
                    "mbet_threshold": mbet,
                    "model_architecture": matrix_type.strip(),
                    "mode":         args.mode,
                    "config_source": config.get("_source", "unknown"),
                    "tier":         config.get("_tier", "unknown"),
                    "timestamp":    datetime.now(ET_TZ).isoformat(),
                    "match_center": {
                        "h2h": h2h,
                        "recentH": recentH,
                        "recentA": recentA,
                        "full_standings": league_standings_data,
                        "statsH": {
                            "played": sH.get("current_season_games", sH.get("played", sH.get("games_played", 0))) if sH else 0,
                            "current_season_games": sH.get("current_season_games", sH.get("played", sH.get("games_played", 0))) if sH else 0,
                            "model_games": sH.get("games_played", 0) if sH else 0,
                            "win_pct": sH.get("win_pct", 0) if sH else 0,
                            "scored": sH.get("adj_off", 0) if sH else 0,
                            "conceded": sH.get("adj_def", 0) if sH else 0,
                            "rank": sH.get("rank") if sH else None,
                            "prior_blended": bool(sH.get("prior_blended")) if sH else False,
                        },
                        "statsA": {
                            "played": sA.get("current_season_games", sA.get("played", sA.get("games_played", 0))) if sA else 0,
                            "current_season_games": sA.get("current_season_games", sA.get("played", sA.get("games_played", 0))) if sA else 0,
                            "model_games": sA.get("games_played", 0) if sA else 0,
                            "win_pct": sA.get("win_pct", 0) if sA else 0,
                            "scored": sA.get("adj_off", 0) if sA else 0,
                            "conceded": sA.get("adj_def", 0) if sA else 0,
                            "rank": sA.get("rank") if sA else None,
                            "prior_blended": bool(sA.get("prior_blended")) if sA else False,
                        }
                    }
                })
            total_predicted += 1

        print()

    # Summary
    print("=" * 70)
    print(f"  COMPLETE: {total_predicted} predictions  |  {total_skipped} skipped")
    print("=" * 70)

    # FIX 16: --validate flag — sanity check top/bottom projections
    if getattr(args, 'validate', False) and all_predictions:
        scored = [(p.get('model_total', 0), f"{p.get('away', '?')} @ {p.get('home', '?')}", p.get('league', '?')) for p in all_predictions if p.get('model_total')]
        scored.sort(key=lambda x: x[0], reverse=True)
        print("\n  ── VALIDATION: Top 5 Highest ──")
        for total, matchup, league in scored[:5]:
            print(f"    {total:>6.1f}  {matchup}  ({league})")
        print("  ── VALIDATION: Top 5 Lowest ──")
        for total, matchup, league in scored[-5:]:
            print(f"    {total:>6.1f}  {matchup}  ({league})")

    # Save Skipped Issues Log
    if skipped_issues:
        error_log_path = f"data/basketball/errors_{date_str}.log"
        os.makedirs(os.path.dirname(error_log_path), exist_ok=True)
        with open(error_log_path, "w", encoding="utf-8") as f:
            f.write(f"--- SKIPPED LEAGUES & ERRORS ({date_str}) ---\n")
            for issue in skipped_issues:
                f.write(f"{issue}\n")
        print(f"\n  Logged {len(skipped_issues)} issue(s) to {error_log_path}")

    # Save
    if all_predictions:
        out_path = f"data/basketball/universal_predictions_{date_str}.json"
        save_json(out_path, {
            "date": date_str,
            "mode": args.mode,
            "total_predictions": total_predicted,
            "predictions": all_predictions,
        })
        print(f"\n  Saved -> {out_path}")

    print()


if __name__ == "__main__":
    main()
